services:
   postgres:
    image: postgres:16.1
    environment:
    - POSTGRES_DB=${DATABASE_DB}
    - POSTGRES_USER=${DATABASE_USERNAME}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
    - 5433:${DATABASE_PORT}
   pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=user@domain.com
    - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
    - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    ports:
     - 80:80
