services:
   postgres:
    image: postgres:16.1
    environment:
    - POSTGRES_DB=${DATABASE_DB}
    - POSTGRES_USER=${DATABASE_USERNAME}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
    - 5433:${DATABASE_PORT}
